[package]
name = "frame_graph"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvark@mozilla.com>"]

[dependencies]
gfx-hal = { path = "../../gfx/src/hal" }

[dev-dependencies]
gfx-backend-vulkan = { path = "../../gfx/src/backend/vulkan" }
